services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak_password"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: "INFO"
    ports:
      - "8123:8080"
    depends_on:
      - db
    command: start
    networks:
      - keycloak-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak_password"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

volumes:
  db_data:

networks:
  keycloak-network:
    driver: bridge
